// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StorageNET20.Data;

namespace StorageNET20.Migrations
{
    [DbContext(typeof(StorageNET20Context))]
    partial class StorageNET20ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StorageNET20.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Shelf")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Mobile",
                            Count = 156,
                            Description = "Stupid",
                            Name = "Iphone",
                            OrderDate = new DateTime(2020, 10, 2, 13, 55, 3, 993, DateTimeKind.Local).AddTicks(1902),
                            Price = 15600,
                            Shelf = "4B"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Mobile",
                            Count = 98,
                            Description = "Better",
                            Name = "S10",
                            OrderDate = new DateTime(2020, 9, 15, 13, 55, 3, 996, DateTimeKind.Local).AddTicks(5499),
                            Price = 12450,
                            Shelf = "4C"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Computers",
                            Count = 23,
                            Description = "Stupid",
                            Name = "MacBook",
                            OrderDate = new DateTime(2020, 10, 3, 13, 55, 3, 996, DateTimeKind.Local).AddTicks(5563),
                            Price = 45600,
                            Shelf = "4C"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Computer",
                            Count = 32,
                            Description = "Stupid",
                            Name = "Suface X",
                            OrderDate = new DateTime(2020, 8, 29, 13, 55, 3, 996, DateTimeKind.Local).AddTicks(5722),
                            Price = 26850,
                            Shelf = "5C"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Office Supplies",
                            Count = 15651,
                            Description = "Stupid",
                            Name = "Pen",
                            OrderDate = new DateTime(2020, 10, 2, 13, 55, 3, 996, DateTimeKind.Local).AddTicks(5725),
                            Price = 1,
                            Shelf = "45W"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
